django_form/django_form/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
]

django_form/user/urls.py
from django.urls import path 
from . import views 
urlpatterns = [ 
    path('', views.formName),
    path('your-name', views.get_name),
    path('thanks', views.thanks),
    path('form-email', views.formMail),
    path('send-email', views.sendMail),
]

django_form/user/models.py
from django.db import models

# Create your models here.

django_form/user/forms.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
    

django_form/user/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.mail import send_mail
from .forms import NameForm,ContactForm


def formName(request):
    return render(request, "user/form-name.html")


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(form.data)
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect("thanks")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, "user/name.html", {"form": form})

def thanks(request):
    return render(request, "user/thanks.html")

def formMail(request):
    return render(request, "user/form-email.html")

def sendMail(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["sender"]
            cc_myself = form.cleaned_data["cc_myself"]

        recipients = ["anpro1346@gmail.com"]
        if cc_myself:
            recipients.append(sender)

        send_mail(subject, message, sender, recipients)
    return HttpResponseRedirect("thanks")

django_form/user/templates/user/form-email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Your Name</h1>
    <!-- templates/my_form.html -->

    <form method="post" action="send-email">
        {% csrf_token %}

        <label for="id_subject">Subject:</label>
        <input type="text" name="subject" id="id_subject" required>

        <label for="id_message">Message:</label>
        <textarea name="message" id="id_message" required></textarea>

        <label for="id_sender">Sender:</label>
        <input type="email" name="sender" id="id_sender" required>

        <input type="checkbox" name="cc_myself" id="id_cc_myself">
        <label for="id_cc_myself">Send a copy to myself</label>

        <button type="submit">Submit</button>
    </form>

    <br>
    <!-- <a href="your-name">qua Name</a> -->
</body>

</html>

django_form/user/templates/user/form-name.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Your Name</h1>
    <form action="your-name" method="post">
        {% csrf_token %}
        <label for="your_name">Your name: </label>
        <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
        <input type="submit" value="OK">
    </form>
    <br>
    <a href="your-name">qua Name</a>
</body>

</html>

django_form/user/templates/user/name.html
<form action="your-name" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

django_form/user/templates/user/thanks.html
<h1>Thank you</h1>